/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcreditacoesRouteImport } from './routes/acreditacoes'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as CapacitacaoRouteImport } from './routes/capacitacao'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EspecializacoesRouteImport } from './routes/especializacoes'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes.index'
import { Route as SolucoesEdificacoesRouteImport } from './routes/solucoes.edificacoes'
import { Route as SolucoesInfraestruturaRouteImport } from './routes/solucoes.infraestrutura'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcreditacoesRoute = AcreditacoesRouteImport.update({
  id: '/acreditacoes',
  path: '/acreditacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacitacaoRoute = CapacitacaoRouteImport.update({
  id: '/capacitacao',
  path: '/capacitacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecializacoesRoute = EspecializacoesRouteImport.update({
  id: '/especializacoes',
  path: '/especializacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolucoesRoute,
} as any)
const SolucoesEdificacoesRoute = SolucoesEdificacoesRouteImport.update({
  id: '/edificacoes',
  path: '/edificacoes',
  getParentRoute: () => SolucoesRoute,
} as any)
const SolucoesInfraestruturaRoute = SolucoesInfraestruturaRouteImport.update({
  id: '/infraestrutura',
  path: '/infraestrutura',
  getParentRoute: () => SolucoesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acreditacoes': typeof AcreditacoesRoute
  '/briefing': typeof BriefingRoute
  '/capacitacao': typeof CapacitacaoRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/especializacoes': typeof EspecializacoesRoute
  '/eventos': typeof EventosRoute
  '/institucional': typeof InstitucionalRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/solucoes': typeof SolucoesRouteWithChildren
  '/solucoes/edificacoes': typeof SolucoesEdificacoesRoute
  '/solucoes/infraestrutura': typeof SolucoesInfraestruturaRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acreditacoes': typeof AcreditacoesRoute
  '/briefing': typeof BriefingRoute
  '/capacitacao': typeof CapacitacaoRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/especializacoes': typeof EspecializacoesRoute
  '/eventos': typeof EventosRoute
  '/institucional': typeof InstitucionalRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/solucoes/edificacoes': typeof SolucoesEdificacoesRoute
  '/solucoes/infraestrutura': typeof SolucoesInfraestruturaRoute
  '/solucoes': typeof SolucoesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acreditacoes': typeof AcreditacoesRoute
  '/briefing': typeof BriefingRoute
  '/capacitacao': typeof CapacitacaoRoute
  '/cases': typeof CasesRoute
  '/contato': typeof ContatoRoute
  '/especializacoes': typeof EspecializacoesRoute
  '/eventos': typeof EventosRoute
  '/institucional': typeof InstitucionalRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/solucoes': typeof SolucoesRouteWithChildren
  '/solucoes/edificacoes': typeof SolucoesEdificacoesRoute
  '/solucoes/infraestrutura': typeof SolucoesInfraestruturaRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acreditacoes'
    | '/briefing'
    | '/capacitacao'
    | '/cases'
    | '/contato'
    | '/especializacoes'
    | '/eventos'
    | '/institucional'
    | '/login'
    | '/portal'
    | '/solucoes'
    | '/solucoes/edificacoes'
    | '/solucoes/infraestrutura'
    | '/solucoes/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acreditacoes'
    | '/briefing'
    | '/capacitacao'
    | '/cases'
    | '/contato'
    | '/especializacoes'
    | '/eventos'
    | '/institucional'
    | '/login'
    | '/portal'
    | '/solucoes/edificacoes'
    | '/solucoes/infraestrutura'
    | '/solucoes'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/acreditacoes'
    | '/briefing'
    | '/capacitacao'
    | '/cases'
    | '/contato'
    | '/especializacoes'
    | '/eventos'
    | '/institucional'
    | '/login'
    | '/portal'
    | '/solucoes'
    | '/solucoes/edificacoes'
    | '/solucoes/infraestrutura'
    | '/solucoes/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcreditacoesRoute: typeof AcreditacoesRoute
  BriefingRoute: typeof BriefingRoute
  CapacitacaoRoute: typeof CapacitacaoRoute
  CasesRoute: typeof CasesRoute
  ContatoRoute: typeof ContatoRoute
  EspecializacoesRoute: typeof EspecializacoesRoute
  EventosRoute: typeof EventosRoute
  InstitucionalRoute: typeof InstitucionalRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  SolucoesRoute: typeof SolucoesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acreditacoes': {
      id: '/acreditacoes'
      path: '/acreditacoes'
      fullPath: '/acreditacoes'
      preLoaderRoute: typeof AcreditacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacitacao': {
      id: '/capacitacao'
      path: '/capacitacao'
      fullPath: '/capacitacao'
      preLoaderRoute: typeof CapacitacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especializacoes': {
      id: '/especializacoes'
      path: '/especializacoes'
      fullPath: '/especializacoes'
      preLoaderRoute: typeof EspecializacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/solucoes/edificacoes': {
      id: '/solucoes/edificacoes'
      path: '/edificacoes'
      fullPath: '/solucoes/edificacoes'
      preLoaderRoute: typeof SolucoesEdificacoesRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/solucoes/infraestrutura': {
      id: '/solucoes/infraestrutura'
      path: '/infraestrutura'
      fullPath: '/solucoes/infraestrutura'
      preLoaderRoute: typeof SolucoesInfraestruturaRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SolucoesRouteChildren {
  SolucoesEdificacoesRoute: typeof SolucoesEdificacoesRoute
  SolucoesInfraestruturaRoute: typeof SolucoesInfraestruturaRoute
  SolucoesIndexRoute: typeof SolucoesIndexRoute
}

const SolucoesRouteChildren: SolucoesRouteChildren = {
  SolucoesEdificacoesRoute: SolucoesEdificacoesRoute,
  SolucoesInfraestruturaRoute: SolucoesInfraestruturaRoute,
  SolucoesIndexRoute: SolucoesIndexRoute,
}

const SolucoesRouteWithChildren = SolucoesRoute._addFileChildren(
  SolucoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcreditacoesRoute: AcreditacoesRoute,
  BriefingRoute: BriefingRoute,
  CapacitacaoRoute: CapacitacaoRoute,
  CasesRoute: CasesRoute,
  ContatoRoute: ContatoRoute,
  EspecializacoesRoute: EspecializacoesRoute,
  EventosRoute: EventosRoute,
  InstitucionalRoute: InstitucionalRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  SolucoesRoute: SolucoesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
